anchor_boxes:
  aspect_ratios: ((0.756,1,1.323), (0.756,1,1.323), (0.756,1,1.323), (0.756,1,1.323),
    (0.756,1,1.323))
  auto_size: true
  sizes: ((13, 18, 54), (26, 35, 107), (51, 70, 214), (102, 140, 429), (205, 281,
    858))
augmentations:
  crop: false
  normalization:
    auto_norm: false
    mean: (0.485, 0.456, 0.406)
    std: (0.229, 0.224, 0.225)
  version: 3
backbone:
  add_P2_to_FPN: true
  backbone_layers_nb: 50
  backbone_type: ResNet
  extra_blocks_FPN: LastLevelP6P7
bg_iou_thresh: 0.4
fg_iou_thresh: 0.5
iou_threshold: 0.3
learning_rate:
  decay:
    gamma: 0.1
    step_size: 100
  policy: plateau
  warmup:
    last_step: 5
    warmup_period: 2
loss:
  bbox_regression: 0.5
  classification: 0.5
version: 2
