loss:
  bbox_regression: 0.5
  classification: 0.5

learning_rate:
  policy: plateau
  warmup:
    last_step: 5
    warmup_period: 2
  decay:
    step_size: 100
    gamma: 0.1

augmentations:
  version: 3
  crop: False
  normalization:
    mean: (0.485, 0.456, 0.406)
    std: (0.229, 0.224, 0.225)
    auto_norm: False

anchor_boxes:
  sizes: ((13, 18, 54), (26, 35, 107), (51, 70, 214), (102, 140, 429), (205, 281, 858))
  aspect_ratios: ((0.756,1,1.323), (0.756,1,1.323), (0.756,1,1.323), (0.756,1,1.323), (0.756,1,1.323))
  auto_size: True

fg_iou_thresh: 0.5
bg_iou_thresh: 0.4
iou_threshold: 0.3
version: 2

backbone:
  backbone_type: ResNet
  backbone_layers_nb: 18
  add_P2_to_FPN: True
  extra_blocks_FPN: LastLevelP6P7